# Site settings
title: Ali Taylor | Product Designer in Amsterdam
email: hello@alastairtaylor.com
description: 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wwww.alitaylor.nl" # the base hostname & protocol for your site
twitter_username: hellomrtaylor
github_username: hellomrtaylor

# Build settings
markdown: kramdown

